name: Deploy Shiny Quarto

on:
  repository_dispatch:
    types: [deploy-shiny]
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "data/**"
      - "scripts/*.qmd"
      - "scripts/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'    # ersion support√©e par shinyapps.io
          use-public-rspm: true
          
      - name: Check R version
        run: |
          R -q -e "sessionInfo()"

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          packages:
            any::tidyverse
            any::jsonlite
            any::plotly
            any::scales
            any::gt
            any::gtExtras
            any::janitor
            any::sf
            any::leaflet
            any::leafem
            any::leaflet.extras2
            any::shiny
            any::rvest
            any::glue
            any::DT
            any::bslib
            any::bsicons
            any::geojsonR
            any::ggtext
            any::leafpop
            any::mapview
            any::rio
            any::rsconnect
            any::cpp11
            any::geometries
            any::jsonify
            any::progress
            any::rapidjsonr
            any::RcppArmadillo
            any::sfheaders
            any::devtools
            
      - name: Install rrapply from github
        env:
          GITHUB_PAT: ${{ secrets.PAT_GITHUB }}
        run: |
          R -e "devtools::install_github('JorisChau/rrapply')"

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_NAME: ${{ secrets.SHINYAPPS_NAME }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          R -e "rsconnect::setAccountInfo(name='$SHINYAPPS_NAME', token='$SHINYAPPS_TOKEN', secret='$SHINYAPPS_SECRET')"
          R -e "rsconnect::deployApp(appDir='scripts', appPrimaryDoc='application_OET.qmd', appName='Progress_MapYourGrid', forceUpdate = TRUE)"

