name: Deploy Shiny Quarto

on:
  repository_dispatch:
    types: [deploy-shiny]
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "data/**"
      - "scripts/*.qmd"
      - "scripts/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Force CRAN repo
        run: |
          echo "options(repos = c(CRAN='https://cloud.r-project.org'))" >> ~/.Rprofile

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'

      - name: Check R version
        run: R -q -e "sessionInfo()"
        
      - name: Restore renv cache
        uses: r-lib/actions/setup-renv@v2
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_NAME: ${{ secrets.SHINYAPPS_NAME }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          Rscript scripts/deploy.R

