name: Deploy Shiny Quarto

on:
  repository_dispatch:
    types: [deploy-shiny]
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "data/**"
      - "scripts/*.qmd"
      - "scripts/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Force CRAN repo
        run: |
          echo "options(repos = c(CRAN='https://cloud.r-project.org'))" >> ~/.Rprofile

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'

      - name: Check R version
        run: R -q -e "sessionInfo()"

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          #cache-version: 2
          packages:
            any::tidyverse
            any::jsonlite
            any::plotly
            any::gt
            any::gtExtras
            any::janitor
            any::leaflet
            any::DT
            any::leafem
            any::leaflet.extras2
            any::rvest
            any::glue
            any::bslib
            any::leafpop
            any::mapview
            any::rio
            any::rsconnect
            any::ggtext
            any::BiocManager
            #any::cpp11
            #any::geometries
            #any::jsonify
            #any::progress
            #any::rapidjsonr
            #any::RcppArmadillo
            #any::sfheaders

      - name: Install GitHub-only packages
        env:
          GITHUB_PAT: ${{ secrets.PAT_GITHUB }}
        run: |
          R -e "install.packages('devtools', repos='https://cloud.r-project.org')"
          R -e "install.packages('remotes', repos='https://cloud.r-project.org')"
          R -e "devtools::install_github('JorisChau/rrapply')"
          R -e "remotes::install_github('mlampros/geojsonR')"

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_NAME: ${{ secrets.SHINYAPPS_NAME }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          Rscript scripts/deploy.R

