name: Run R script daily

on:
  workflow_dispatch:
  schedule:
    # en hiver, 13h30 cron = 14h30 local. En Ã©tÃ©, 13h30 cron = 15h30 local
    - cron: "30 09 * * *"

jobs:
  run-rmd-script:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'
          use-public-rspm: true

      - name: Force CRAN repo
        run: |
          echo "options(repos = c(CRAN='https://cloud.r-project.org'))" >> ~/.Rprofile

      - name: Restore renv environment
        uses: r-lib/actions/setup-renv@v2

      - name: Run R script
        run: Rscript scripts/import_data_dashboard.R

      - name: Commit updated data
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add data/
          git commit -m "ðŸ“¦ Update data" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
